Repository I2PC/scipion-em-xmipp, pull requests merged in 2023-04, with the labels that each got.

#649 Installation DLTK
  xmipp3/__init__.py
Labels: In progress

#656 Movie gain protocol: bug fix a print format
  xmipp3/protocols/protocol_movie_gain.py
Labels: bug

#659 Updated requirement. HotFix
  requirements.txt
  xmipp3/__init__.py
Labels: release
