Repository I2PC/scipion-em-xmipp, pull requests merged in 2025-06, with the labels that each got.

#932 Extract particles protocol: force output boxsize
  xmipp3/protocols/protocol_extract_particles.py
  xmipp3/protocols/protocol_movie_dose_analysis.py
Labels: enhancement

#962 Release 3.25.06 to devel
  xmipp3/version.py
  xmipp3/viewers/viewer_structure_map.py
Labels: release

#960 Fixed validation and default value handling in extract assymetric unit
  xmipp3/protocols/protocol_extract_asymmetric_unit.py
Labels: bug
